### ISSUE TITLE
PaymentLog event not supported and deserialization crashes with NPE

### ISSUE THREAD

**Issue by sbailliez** [EasyPost/easypost-java#36]
Trying to deserialize a payment log event crashes with NullPointerException

```
! java.lang.NullPointerException: null
! at com.google.gson.internal.$Gson$Preconditions.checkNotNull($Gson$Preconditions.java:39)
! at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72)
! at com.google.gson.reflect.TypeToken.get(TypeToken.java:296)
! at com.google.gson.Gson.fromJson(Gson.java:885)
! at com.google.gson.Gson.fromJson(Gson.java:952)
! at com.google.gson.Gson.fromJson(Gson.java:925)
! at com.easypost.model.EventDeserializer.deserialize(EventDeserializer.java:101)
! at com.easypost.model.EventDeserializer.deserialize(EventDeserializer.java:18)
! at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
! at com.google.gson.Gson.fromJson(Gson.java:887)
! at com.google.gson.Gson.fromJson(Gson.java:852)
! at com.google.gson.Gson.fromJson(Gson.java:801)
! at com.google.gson.Gson.fromJson(Gson.java:773)
```

The event is similar to:

```
{
  "result": {
    "id": "paylog_8888888888",
    "object": "PaymentLog",
    "source_type": "credit_card",
    "target_type": "easypost_stripe",
    "date": "2017-07-25 21:00:19 UTC",
    "charge_type": "recharge",
    "status": "complete",
    "amount": "999.00000",
    "created_at": "2017-07-25T21:00:19Z",
    "updated_at": "2017-07-25T21:00:19Z",
    "last4": "4396"
  },
  "description": "payment.created",
  "mode": "production",
  "previous_attributes": {},
  "created_at": "2017-07-25T21:00:19Z",
  "pending_urls": [
    "https://foo.com"
  ],
  "completed_urls": [],
  "updated_at": "2017-07-25T21:00:19Z",
  "id": "evt_11111111",
  "user_id": "user_xxxxx",
  "status": "in_queue",
  "object": "Event"
}
```

**Comment by Justintime50** [comment]
@sbailliez is this still an issue in recent versions of this library? If so, can you provide a small code snippet on how to reproduce this issue?

**Comment by jchen293** [comment]
@sbailliez Are you still getting this issue with the latest version? We do like to investigate this issue, could you send us a snippet of Java code that arises from this exception?

**Comment by Justintime50** [comment]
Closing due to inactivity and the inability to reproduce.
